name: 'cas notarize docker image'
description: 'Uses the cas CLI to notarize docker images'
branding:
  icon: 'lock'
  color: 'green'
inputs:
  asset:
    description: 'Asset to notarize'
    required: true
  cas_api_key:
    description: 'API Key provided upon signing up through cas.codenotary.com'
    required: true
runs:
  using: 'docker'
  image: 'docker://codenotary/cas:bom-docker'
  args:
    - n
    - ${{ inputs.asset }}
    - --api-key=${{ inputs.cas_api_key }}
