name: notarize-docker-image

on:
  push:
    branches: [main]

jobs:
  notarize-docker-image:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      #--> Build Docker image and push it to the local registry- checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.review.commit_id }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build Docker image and push it to the local registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: localhost:5000/codenotary/hello-cas-world:latest
      #<--

      - name: Notarize Docker image
        #--> Run the GitHub action
        # uses: codenotary/cas-notarize-docker-image-github-action@v1.0.0
        uses: codenotary/cas-notarize-docker-image-github-action@main
        with:
          # make it notarize it's own Docker image B-)
          asset: docker://codenotary/hello-cas-world:latest
          cas_api_key: ${{ secrets.CAS_API_KEY }}